// <auto-generated />
using System;
using CarOwnerDealershipDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab5CarOwnerDealershipDB.Migrations
{
    [DbContext(typeof(CarOwnerDealershipContext))]
    partial class CarOwnerDealershipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CarOwnerDealershipDB.Models.Car", b =>
                {
                    b.Property<int>("carID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("dealershipID")
                        .HasColumnType("int");

                    b.Property<int>("kilometers")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastSoldDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ownerID")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("carID");

                    b.HasIndex("dealershipID");

                    b.HasIndex("ownerID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarOwnerDealershipDB.Models.Dealership", b =>
                {
                    b.Property<int>("dealershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dealershipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("province")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dealershipID");

                    b.ToTable("Dealerships");
                });

            modelBuilder.Entity("CarOwnerDealershipDB.Models.Owner", b =>
                {
                    b.Property<int>("ownerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("driversLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ownerID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("CarOwnerDealershipDB.Models.Car", b =>
                {
                    b.HasOne("CarOwnerDealershipDB.Models.Dealership", "dealership")
                        .WithMany("cars")
                        .HasForeignKey("dealershipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarOwnerDealershipDB.Models.Owner", "owner")
                        .WithMany("cars")
                        .HasForeignKey("ownerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dealership");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("CarOwnerDealershipDB.Models.Dealership", b =>
                {
                    b.Navigation("cars");
                });

            modelBuilder.Entity("CarOwnerDealershipDB.Models.Owner", b =>
                {
                    b.Navigation("cars");
                });
#pragma warning restore 612, 618
        }
    }
}
